# name: Deploy

# on:
#   push:
#     paths-ignore:
#       - .github/*
#     branches:
#       - master

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - name: Deploy newest version
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.HOST }}
#         USERNAME: ${{ secrets.USERNAME }}
#         PORT: ${{ secrets.PORT }}
#         KEY: ${{ secrets.SSHKEY }}
#         script:  |
#           cd pycharity
#           git fetch
#           git reset origin/master --hard
#           docker-compose down
#           docker-compose up --build -d
